/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tarea01di;

/**
 *
 * @author tpmvo
 */
public class ReservaJDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReservaJDialog.class.getName());

    /**
     * Creates new form ReservaJDialog
     */
    public ReservaJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoReserva = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        pnlCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cbPais = new javax.swing.JComboBox<>();
        txtPrefijo = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        pnlReserva = new javax.swing.JPanel();
        lvlFechaReserva = new javax.swing.JLabel();
        lvlHoraReserva = new javax.swing.JLabel();
        lvlTipoReserva = new javax.swing.JLabel();
        spnFecha = new javax.swing.JSpinner();
        cbHora = new javax.swing.JComboBox<>();
        rbClase = new javax.swing.JRadioButton();
        rbLiga = new javax.swing.JRadioButton();
        rbAmistoso = new javax.swing.JRadioButton();
        lblNivel = new javax.swing.JLabel();
        lblAbierto = new javax.swing.JLabel();
        lblNumPlazas = new javax.swing.JLabel();
        spnNivel = new javax.swing.JSpinner();
        chkPartidoAbierto = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        sldPlazasLibres = new javax.swing.JSlider();
        btnVolver = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 51, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Club de Pádel - Nueva Reserva");
        lblTitulo.setToolTipText("Título");

        pnlCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N
        pnlCliente.setForeground(new java.awt.Color(0, 102, 204));
        pnlCliente.setToolTipText("Panel de datos del cliente");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Nombre:");
        jLabel1.setToolTipText("Nombre del cliente");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Teléfono:");
        jLabel2.setToolTipText("Teléfono del cliente");

        txtNombre.setToolTipText("Introduzca el nombre completo");
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        cbPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ES", "PT", "FR" }));
        cbPais.setToolTipText("Seleccione el país para la asignación del prefijo");
        cbPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaisActionPerformed(evt);
            }
        });

        txtPrefijo.setEditable(false);
        txtPrefijo.setText("+34");
        txtPrefijo.setToolTipText("Se asigna automáticamente en función de la selección del país");
        txtPrefijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrefijoActionPerformed(evt);
            }
        });

        txtNumero.setToolTipText("Introduzca el número de teléfono sin  el prefijo");

        javax.swing.GroupLayout pnlClienteLayout = new javax.swing.GroupLayout(pnlCliente);
        pnlCliente.setLayout(pnlClienteLayout);
        pnlClienteLayout.setHorizontalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(59, 59, 59)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addComponent(cbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrefijo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombre))
                .addContainerGap())
        );
        pnlClienteLayout.setVerticalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrefijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnlReserva.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la reserva", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N
        pnlReserva.setToolTipText("Panel de datos de la reserva");

        lvlFechaReserva.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lvlFechaReserva.setText("Fecha de reserva:");
        lvlFechaReserva.setToolTipText("Fecha de la reserva");

        lvlHoraReserva.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lvlHoraReserva.setText("Hora de reserva:");
        lvlHoraReserva.setToolTipText("Hora de la reserva");

        lvlTipoReserva.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lvlTipoReserva.setText("Tipo de reserva:");
        lvlTipoReserva.setToolTipText("Tipo de la reserva");

        spnFecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.ERA));
        spnFecha.setToolTipText("Introduzca fecha de la reserva");
        spnFecha.setEditor(new javax.swing.JSpinner.DateEditor(spnFecha, "dd/MM/yyyy"));

        cbHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "17:00", "18:30", "20:00", "21:30" }));
        cbHora.setToolTipText("Seleccione uno de los turnos disponibles");
        cbHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHoraActionPerformed(evt);
            }
        });

        grupoTipoReserva.add(rbClase);
        rbClase.setText("Clase");
        rbClase.setToolTipText("Reserva de tipo clase");
        rbClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbClaseActionPerformed(evt);
            }
        });

        grupoTipoReserva.add(rbLiga);
        rbLiga.setText("Liga");
        rbLiga.setToolTipText("Reserva de tipo liga");
        rbLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLigaActionPerformed(evt);
            }
        });

        grupoTipoReserva.add(rbAmistoso);
        rbAmistoso.setText("Amistoso");
        rbAmistoso.setToolTipText("Reserva de tipo amistoso");
        rbAmistoso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAmistosoActionPerformed(evt);
            }
        });

        lblNivel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblNivel.setText("Nivel de partido amistoso:");
        lblNivel.setToolTipText("Nivel del partido amistoso");

        lblAbierto.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblAbierto.setText("Partido abierto:");
        lblAbierto.setToolTipText("Partido abierto");

        lblNumPlazas.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblNumPlazas.setText("Nº plazas libres:");
        lblNumPlazas.setToolTipText("Nº plazas libres");

        spnNivel.setModel(new javax.swing.SpinnerListModel(new String[] {"Iniciación", "Medio", "Medio-alto", "Alto"}));
        spnNivel.setToolTipText("Indique el nivel de los jugadores");

        chkPartidoAbierto.setText("(Los jugadores se pueden apuntar por la web)");
        chkPartidoAbierto.setToolTipText("Marque si busca jugadores externos en la web");
        chkPartidoAbierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPartidoAbiertoActionPerformed(evt);
            }
        });

        jSeparator1.setToolTipText("Separador del panel de datos de reserva");

        sldPlazasLibres.setMajorTickSpacing(1);
        sldPlazasLibres.setMaximum(3);
        sldPlazasLibres.setMinimum(1);
        sldPlazasLibres.setPaintLabels(true);
        sldPlazasLibres.setPaintTicks(true);
        sldPlazasLibres.setSnapToTicks(true);
        sldPlazasLibres.setToolTipText("Seleccione las plazas libres");
        sldPlazasLibres.setValue(1);
        sldPlazasLibres.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout pnlReservaLayout = new javax.swing.GroupLayout(pnlReserva);
        pnlReserva.setLayout(pnlReservaLayout);
        pnlReservaLayout.setHorizontalGroup(
            pnlReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReservaLayout.createSequentialGroup()
                        .addGroup(pnlReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNivel)
                            .addComponent(lblAbierto)
                            .addComponent(lblNumPlazas))
                        .addGap(65, 65, 65)
                        .addGroup(pnlReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkPartidoAbierto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sldPlazasLibres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spnNivel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReservaLayout.createSequentialGroup()
                        .addGroup(pnlReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lvlFechaReserva)
                            .addComponent(lvlHoraReserva)
                            .addGroup(pnlReservaLayout.createSequentialGroup()
                                .addComponent(lvlTipoReserva)
                                .addGap(107, 107, 107)
                                .addComponent(rbClase, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbAmistoso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(spnFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                .addComponent(cbHora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(pnlReservaLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlReservaLayout.setVerticalGroup(
            pnlReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lvlFechaReserva)
                    .addComponent(spnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlHoraReserva)
                    .addComponent(cbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlTipoReserva)
                    .addComponent(rbClase)
                    .addComponent(rbLiga)
                    .addComponent(rbAmistoso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(pnlReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNivel)
                    .addComponent(spnNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAbierto)
                    .addComponent(chkPartidoAbierto))
                .addGap(18, 18, 18)
                .addGroup(pnlReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumPlazas)
                    .addComponent(sldPlazasLibres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        gestionarCamposAmistoso();
        gestionarCamposAmistoso();
        gestionarCamposAmistoso();

        btnVolver.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnEnviar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnEnviar.setText("Enviar Reserva");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
            .addComponent(pnlCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void cbPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaisActionPerformed

        // Obtenemos el texto de la opción seleccionada
        String seleccion = cbPais.getSelectedItem().toString();

        // Estructura para asignar el prefijo según el país
        // Estructura para asignar el prefijo según el país
        switch (seleccion) {
            case "ES":
                txtPrefijo.setText("+34");
                break;
            case "FR":
                txtPrefijo.setText("+33");
                break;
            case "PT":
                txtPrefijo.setText("+351");
                break;
            default:
                txtPrefijo.setText("");
                break;
        }
    }//GEN-LAST:event_cbPaisActionPerformed

    private void txtPrefijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrefijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrefijoActionPerformed

    private void cbHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbHoraActionPerformed

    private void rbClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbClaseActionPerformed
        gestionarCamposAmistoso();
    }//GEN-LAST:event_rbClaseActionPerformed

    private void rbLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLigaActionPerformed
        gestionarCamposAmistoso();
    }//GEN-LAST:event_rbLigaActionPerformed

    private void rbAmistosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAmistosoActionPerformed
        gestionarCamposAmistoso();
    }//GEN-LAST:event_rbAmistosoActionPerformed

    private void chkPartidoAbiertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPartidoAbiertoActionPerformed
        gestionarCamposAmistoso();
    }//GEN-LAST:event_chkPartidoAbiertoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed

        // 1. Extraer la fecha y darle formato de texto para el mensaje
        // Aunque el Spinner solo muestre dd/MM/yyyy, getValue() devuelve un objeto Date complejo
        java.text.SimpleDateFormat formato = new java.text.SimpleDateFormat("dd/MM/yyyy");
        String fechaSeleccionada = formato.format(spnFecha.getValue());

        // 2. Extraer la hora seleccionada del ComboBox
        String horaSeleccionada = cbHora.getSelectedItem().toString();

        // 3. Extraer el nombre para personalizar el mensaje
        String cliente = txtNombre.getText();

        // 4. Construir el cuerpo del mensaje
        String mensaje = "Reserva confirmada con éxito.\n\n"
                + "Cliente: " + cliente + "\n"
                + "Fecha: " + fechaSeleccionada + "\n"
                + "Hora: " + horaSeleccionada;

        // 5. Mostrar el mensaje al usuario
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Confirmación de Reserva", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // 6. Cerrar el diálogo
        this.dispose();
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    private void gestionarCamposAmistoso() {
        // Esta línea es la clave: devuelve 'true' solo si Amistoso está marcado
        boolean esAmistoso = rbAmistoso.isSelected();

        // Si esAmistoso es false (porque está pulsado Liga o Clase), se deshabilitan:
        spnNivel.setEnabled(esAmistoso);
        chkPartidoAbierto.setEnabled(esAmistoso);

        // Lógica para el Slider de plazas
        if (esAmistoso && chkPartidoAbierto.isSelected()) {
            sldPlazasLibres.setEnabled(true);
        } else {
            sldPlazasLibres.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbHora;
    private javax.swing.JComboBox<String> cbPais;
    private javax.swing.JCheckBox chkPartidoAbierto;
    private javax.swing.ButtonGroup grupoTipoReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAbierto;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNumPlazas;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lvlFechaReserva;
    private javax.swing.JLabel lvlHoraReserva;
    private javax.swing.JLabel lvlTipoReserva;
    private javax.swing.JPanel pnlCliente;
    private javax.swing.JPanel pnlReserva;
    private javax.swing.JRadioButton rbAmistoso;
    private javax.swing.JRadioButton rbClase;
    private javax.swing.JRadioButton rbLiga;
    private javax.swing.JSlider sldPlazasLibres;
    private javax.swing.JSpinner spnFecha;
    private javax.swing.JSpinner spnNivel;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPrefijo;
    // End of variables declaration//GEN-END:variables
}
