/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package miscomponentes;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author tpmvo
 */
public class ImagenFondoPanel extends javax.swing.JPanel {

    /**
     * Creates new form ImagenFondoPanel
     */
    public ImagenFondoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagenInicial = new javax.swing.JLabel();
        lblInicial = new javax.swing.JLabel();
        txtRutaInicial = new javax.swing.JTextField();
        btnSeleccionarInicial = new javax.swing.JButton();
        lblOpacidadInicial = new javax.swing.JLabel();
        sldOpacidadInicial = new javax.swing.JSlider();
        jSeparator1 = new javax.swing.JSeparator();
        lblImagenFinal = new javax.swing.JLabel();
        lblFinal = new javax.swing.JLabel();
        txtRutaFinal = new javax.swing.JTextField();
        btnSeleccionarFinal = new javax.swing.JButton();
        lblOpacidadFinal = new javax.swing.JLabel();
        sldOpacidadFinal = new javax.swing.JSlider();

        lblImagenInicial.setText("IMAGEN INICIAL");

        lblInicial.setText("Imagen:");

        txtRutaInicial.setEditable(false);
        txtRutaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaInicialActionPerformed(evt);
            }
        });

        btnSeleccionarInicial.setText("...");
        btnSeleccionarInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarInicialActionPerformed(evt);
            }
        });

        lblOpacidadInicial.setText("Opacidad");

        sldOpacidadInicial.setMajorTickSpacing(20);
        sldOpacidadInicial.setMinorTickSpacing(5);
        sldOpacidadInicial.setPaintLabels(true);
        sldOpacidadInicial.setPaintTicks(true);

        lblImagenFinal.setText("IMAGEN FINAL");

        lblFinal.setText("Imagen:");

        txtRutaFinal.setEditable(false);
        txtRutaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaFinalActionPerformed(evt);
            }
        });

        btnSeleccionarFinal.setText("...");
        btnSeleccionarFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarFinalActionPerformed(evt);
            }
        });

        lblOpacidadFinal.setText("Opacidad");

        sldOpacidadFinal.setMajorTickSpacing(20);
        sldOpacidadFinal.setMinorTickSpacing(5);
        sldOpacidadFinal.setPaintLabels(true);
        sldOpacidadFinal.setPaintTicks(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(lblImagenInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOpacidadInicial)
                            .addComponent(lblInicial))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRutaInicial)
                                .addGap(18, 18, 18)
                                .addComponent(btnSeleccionarInicial))
                            .addComponent(sldOpacidadInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblImagenFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOpacidadFinal)
                            .addComponent(lblFinal))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRutaFinal)
                                .addGap(18, 18, 18)
                                .addComponent(btnSeleccionarFinal))
                            .addComponent(sldOpacidadFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagenInicial)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInicial)
                    .addComponent(txtRutaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionarInicial))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpacidadInicial)
                    .addComponent(sldOpacidadInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblImagenFinal)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFinal)
                    .addComponent(txtRutaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionarFinal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpacidadFinal)
                    .addComponent(sldOpacidadFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Lógica para el botón de la Imagen Inicial
     */
    private void btnSeleccionarInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarInicialActionPerformed
        JFileChooser fc = new JFileChooser();
        int seleccion = fc.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File fichero = fc.getSelectedFile();
            txtRutaInicial.setText(fichero.getAbsolutePath());
        }
    }//GEN-LAST:event_btnSeleccionarInicialActionPerformed
    /**
     * Lógica para el botón de la Imagen Final
     */
    private void btnSeleccionarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarFinalActionPerformed
        JFileChooser fc = new JFileChooser();
        int seleccion = fc.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File fichero = fc.getSelectedFile();
            txtRutaFinal.setText(fichero.getAbsolutePath());
        }
    }//GEN-LAST:event_btnSeleccionarFinalActionPerformed

    private void txtRutaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutaInicialActionPerformed

    private void txtRutaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutaFinalActionPerformed
    /**
     * Devuelve un objeto ImagenFondo con los cuatro parámetros informados.
     */
    public ImagenFondo getSelectedValue() {
        // Creamos los objetos File a partir de lo que hay en los campos de texto
        File rutaIni = new File(txtRutaInicial.getText());
        File rutaFin = new File(txtRutaFinal.getText());

        // Convertimos el valor del Slider (0-100) a float (0.0f - 1.0f)
        float opacidadIni = sldOpacidadInicial.getValue() / 100f;
        float opacidadFin = sldOpacidadFinal.getValue() / 100f;

        // Retornamos el objeto ImagenFondo usando el constructor de 4 parámetros
        return new ImagenFondo(rutaIni, rutaFin, opacidadIni, opacidadFin);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionarFinal;
    private javax.swing.JButton btnSeleccionarInicial;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFinal;
    private javax.swing.JLabel lblImagenFinal;
    private javax.swing.JLabel lblImagenInicial;
    private javax.swing.JLabel lblInicial;
    private javax.swing.JLabel lblOpacidadFinal;
    private javax.swing.JLabel lblOpacidadInicial;
    private javax.swing.JSlider sldOpacidadFinal;
    private javax.swing.JSlider sldOpacidadInicial;
    private javax.swing.JTextField txtRutaFinal;
    private javax.swing.JTextField txtRutaInicial;
    // End of variables declaration//GEN-END:variables
}
