/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package acciones;

import java.sql.Connection;
import java.sql.SQLException;

/**
 *
 * @author Carlos
 */
public class Aplicacion extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Aplicacion.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public Aplicacion() {
        initComponents();
        inicializarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        botonCrear = new javax.swing.JToggleButton();
        botonInsertar = new javax.swing.JToggleButton();
        botonRecuperar = new javax.swing.JToggleButton();
        botonClientes = new javax.swing.JToggleButton();
        botonProductos = new javax.swing.JToggleButton();
        botonPedidos = new javax.swing.JToggleButton();
        botonContinuar = new javax.swing.JToggleButton();
        botonActualizarDatosProductos = new javax.swing.JToggleButton();
        botonActualizarPedidos = new javax.swing.JToggleButton();
        botonActualizarClientes = new javax.swing.JToggleButton();
        botonFabricante1 = new javax.swing.JToggleButton();
        botonSalir = new javax.swing.JToggleButton();
        jScrollPaneMensajes = new javax.swing.JScrollPane();
        textPaneMensajes = new javax.swing.JTextPane();
        jScrollPaneTablas = new javax.swing.JScrollPane();
        textPaneTablas = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTitulo.setText("Opciones de la Aplicación");

        botonCrear.setText("Crear 3 tablas (clientes,pedidos,productos)");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });

        botonInsertar.setText("Insertar en las 3 tablas");
        botonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertarActionPerformed(evt);
            }
        });

        botonRecuperar.setText("Recuperar Datos");
        botonRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRecuperarActionPerformed(evt);
            }
        });

        botonClientes.setText("Clientes");
        botonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClientesActionPerformed(evt);
            }
        });

        botonProductos.setText("Productos");
        botonProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProductosActionPerformed(evt);
            }
        });

        botonPedidos.setText("Pedidos");
        botonPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPedidosActionPerformed(evt);
            }
        });

        botonContinuar.setText("Continuar");
        botonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContinuarActionPerformed(evt);
            }
        });

        botonActualizarDatosProductos.setText("Actualziar datos de los productos");
        botonActualizarDatosProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarDatosProductosActionPerformed(evt);
            }
        });

        botonActualizarPedidos.setText("Actualizar pedidos (sent, preparadas)");
        botonActualizarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarPedidosActionPerformed(evt);
            }
        });

        botonActualizarClientes.setText("Actualizar clientes (sent, preparadas)");
        botonActualizarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarClientesActionPerformed(evt);
            }
        });

        botonFabricante1.setText("Pedidos con el fabricante nº 1");
        botonFabricante1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFabricante1ActionPerformed(evt);
            }
        });

        botonSalir.setText("SALIR");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jScrollPaneMensajes.setViewportView(textPaneMensajes);

        jScrollPaneTablas.setViewportView(textPaneTablas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jScrollPaneMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))))
                            .addComponent(botonCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botonInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                                    .addComponent(botonRecuperar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(botonActualizarDatosProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonActualizarPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonActualizarClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonFabricante1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPaneTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonCrear)
                        .addGap(18, 18, 18)
                        .addComponent(botonInsertar)
                        .addGap(18, 18, 18)
                        .addComponent(botonRecuperar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonClientes)
                            .addComponent(botonProductos)
                            .addComponent(botonPedidos))
                        .addGap(18, 18, 18)
                        .addComponent(botonContinuar)
                        .addGap(30, 30, 30)
                        .addComponent(botonActualizarDatosProductos)
                        .addGap(18, 18, 18)
                        .addComponent(botonActualizarPedidos)
                        .addGap(18, 18, 18)
                        .addComponent(botonActualizarClientes)
                        .addGap(18, 18, 18)
                        .addComponent(botonFabricante1))
                    .addComponent(jScrollPaneTablas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonSalir)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarBotones() {

        botonSalir.setEnabled(true);
        botonCrear.setEnabled(true);
        botonInsertar.setEnabled(false);
        botonRecuperar.setEnabled(false);
        botonClientes.setEnabled(false);
        botonProductos.setEnabled(false);
        botonPedidos.setEnabled(false);
        botonContinuar.setEnabled(false);
        botonActualizarDatosProductos.setEnabled(false);
        botonActualizarPedidos.setEnabled(false);
        botonActualizarClientes.setEnabled(false);
        botonFabricante1.setEnabled(false);
    }
    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        try {
            ConexionBBDD db = new ConexionBBDD();
            db.crearTablas();
            textPaneMensajes.setText("Tablas creadas con éxito.");
        } catch (Exception e) {
            textPaneMensajes.setText("Error de conexión: " + e.getMessage());
        }

        botonCrear.setEnabled(false);
        botonInsertar.setEnabled(true);
        botonSalir.setEnabled(true);
        botonRecuperar.setEnabled(false);
        botonClientes.setEnabled(false);
        botonProductos.setEnabled(false);
        botonPedidos.setEnabled(false);
        botonContinuar.setEnabled(false);
        botonActualizarDatosProductos.setEnabled(false);
        botonActualizarPedidos.setEnabled(false);
        botonActualizarClientes.setEnabled(false);
        botonFabricante1.setEnabled(false);

    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertarActionPerformed
        try {
            ConexionBBDD db = new ConexionBBDD();
            db.insertarRegistros();
            textPaneMensajes.setText("Se han insertado los registros con éxito en las 3 tablas.");

            botonRecuperar.setEnabled(true);
            botonClientes.setEnabled(false);
            botonProductos.setEnabled(false);
            botonPedidos.setEnabled(false);
            botonCrear.setEnabled(false);
            botonContinuar.setEnabled(false);
            botonInsertar.setEnabled(false);
            botonSalir.setEnabled(true);
            botonInsertar.setEnabled(false);
            botonActualizarDatosProductos.setEnabled(false);
            botonActualizarPedidos.setEnabled(false);
            botonActualizarClientes.setEnabled(false);
            botonFabricante1.setEnabled(false);
        } catch (Exception e) {
            textPaneMensajes.setText("Error al insertar contenido" + e.getMessage());
        }
    }//GEN-LAST:event_botonInsertarActionPerformed

    private void botonRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRecuperarActionPerformed
        textPaneMensajes.setText("Selecciona una tabla para visualizar sus registros.");
        botonRecuperar.setEnabled(false);
        botonClientes.setEnabled(true);
        botonProductos.setEnabled(true);
        botonPedidos.setEnabled(true);
        botonContinuar.setEnabled(true);
    }//GEN-LAST:event_botonRecuperarActionPerformed

    private void botonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClientesActionPerformed
        ConexionBBDD db = new ConexionBBDD();
        textPaneTablas.setText(db.obtenerDatosTabla("clientes"));
        textPaneMensajes.setText("Mostrando tabla Clientes.");
    }//GEN-LAST:event_botonClientesActionPerformed

    private void botonProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProductosActionPerformed
        ConexionBBDD db = new ConexionBBDD();
        textPaneTablas.setText(db.obtenerDatosTabla("productos"));
        textPaneMensajes.setText("Mostrando tabla Productos.");
    }//GEN-LAST:event_botonProductosActionPerformed

    private void botonPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPedidosActionPerformed
        ConexionBBDD db = new ConexionBBDD();
        textPaneTablas.setText(db.obtenerDatosTabla("pedidos"));
        textPaneMensajes.setText("Mostrando tabla Pedidos.");
    }//GEN-LAST:event_botonPedidosActionPerformed

    private void botonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContinuarActionPerformed
        textPaneTablas.setText("");
        textPaneMensajes.setText("Fase de consulta finalizada. Iniciando fase de actualizaciones.");
        botonClientes.setEnabled(false);
        botonProductos.setEnabled(false);
        botonPedidos.setEnabled(false);
        botonContinuar.setEnabled(false);
        botonActualizarDatosProductos.setEnabled(true);
    }//GEN-LAST:event_botonContinuarActionPerformed

    private void botonActualizarDatosProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarDatosProductosActionPerformed
        ConexionBBDD db = new ConexionBBDD();

        String resultado = db.actualizarPrecioProducto(3, 500.00);

        textPaneTablas.setText(resultado);
        textPaneMensajes.setText("Precio del producto con ID: 3, se ha actualizado a 500 correctamente.");

        botonActualizarDatosProductos.setEnabled(false);
        botonActualizarPedidos.setEnabled(true);
    }//GEN-LAST:event_botonActualizarDatosProductosActionPerformed

    private void botonActualizarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarPedidosActionPerformed
        ConexionBBDD db = new ConexionBBDD();

        String resultado = db.actualizarImportePedido(1, 15.00);

        textPaneTablas.setText(resultado);
        textPaneMensajes.setText("Importe del pedido con ID: 1, se ha actualizado a 15 correctamente.");

        botonActualizarPedidos.setEnabled(false);
        botonActualizarClientes.setEnabled(true);
    }//GEN-LAST:event_botonActualizarPedidosActionPerformed

    private void botonActualizarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarClientesActionPerformed

        ConexionBBDD db = new ConexionBBDD();

        String resultado = db.actualizarNombreYCredito(2101, "José Pérez", 1000.00);

        textPaneTablas.setText(resultado);
        textPaneMensajes.setText("Nombre y crédito del cliente 2101 actualizados en una sola sentencia.");

        botonActualizarClientes.setEnabled(false);
        botonFabricante1.setEnabled(true);
    }//GEN-LAST:event_botonActualizarClientesActionPerformed

    private void botonFabricante1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFabricante1ActionPerformed

        ConexionBBDD db = new ConexionBBDD();

        String resultado = db.consultaFabricante1();

        textPaneTablas.setText(resultado);
        textPaneMensajes.setText("Consulta del fabricante 1 realizada con éxito.");

        botonFabricante1.setEnabled(false);

    }//GEN-LAST:event_botonFabricante1ActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        try {
            textPaneMensajes.setText("Cerrando aplicación...");
            System.out.println("Conexiones cerradas.");

        } finally {
            System.out.println("Aplicación finalizada correctamente.");
            System.exit(0);
        }
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Aplicacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonActualizarClientes;
    private javax.swing.JToggleButton botonActualizarDatosProductos;
    private javax.swing.JToggleButton botonActualizarPedidos;
    private javax.swing.JToggleButton botonClientes;
    private javax.swing.JToggleButton botonContinuar;
    private javax.swing.JToggleButton botonCrear;
    private javax.swing.JToggleButton botonFabricante1;
    private javax.swing.JToggleButton botonInsertar;
    private javax.swing.JToggleButton botonPedidos;
    private javax.swing.JToggleButton botonProductos;
    private javax.swing.JToggleButton botonRecuperar;
    private javax.swing.JToggleButton botonSalir;
    private javax.swing.JScrollPane jScrollPaneMensajes;
    private javax.swing.JScrollPane jScrollPaneTablas;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextPane textPaneMensajes;
    private javax.swing.JTextPane textPaneTablas;
    // End of variables declaration//GEN-END:variables
}
