package Modelos;
// Generated 06-feb-2026 12:23:40 by Hibernate Tools 4.3.1



/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer idCurso;
     private Profesor profesor;
     private String nombre;

    public Curso() {
    }

	
    public Curso(String nombre) {
        this.nombre = nombre;
    }
    public Curso(Profesor profesor, String nombre) {
       this.profesor = profesor;
       this.nombre = nombre;
    }
   
    public Integer getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(Integer idCurso) {
        this.idCurso = idCurso;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


