package Modelos;
// Generated 06-feb-2026 12:23:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private Integer idProfesor;
     private Departamento departamento;
     private String nombre;
     private String email;
     private Set cursos = new HashSet(0);

    public Profesor() {
    }

	
    public Profesor(String nombre) {
        this.nombre = nombre;
    }
    public Profesor(Departamento departamento, String nombre, String email, Set cursos) {
       this.departamento = departamento;
       this.nombre = nombre;
       this.email = email;
       this.cursos = cursos;
    }
   
    public Integer getIdProfesor() {
        return this.idProfesor;
    }
    
    public void setIdProfesor(Integer idProfesor) {
        this.idProfesor = idProfesor;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }




}


