/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tarea03di;

import java.awt.Color;
import java.util.Locale;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

public class ReservaJDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReservaJDialog.class.getName());

    int xMouse, yMouse;

    public ReservaJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lblEnviar.setEnabled(false);
        ValidationGroup vg = validationPanel1.getValidationGroup();
        vg.add(txtNombre, StringValidators.REQUIRE_NON_EMPTY_STRING);
        vg.add(txtTelefono, StringValidators.REQUIRE_NON_EMPTY_STRING);

        validationPanel1.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                if (validationPanel1.getProblem() == null) {
                    lblEnviar.setEnabled(true);
                } else {
                    lblEnviar.setEnabled(false);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoReserva = new javax.swing.ButtonGroup();
        pnlBackground = new javax.swing.JPanel();
        lblIcono = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblReserva = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        sptNombre = new javax.swing.JSeparator();
        lblTelefono = new javax.swing.JLabel();
        cbPais = new javax.swing.JComboBox<>();
        txtPrefijo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        sptTelefono = new javax.swing.JSeparator();
        lblFecha = new javax.swing.JLabel();
        spnFecha = new javax.swing.JSpinner();
        lblHora = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblNivel = new javax.swing.JLabel();
        lblPlazas = new javax.swing.JLabel();
        lblAbierto = new javax.swing.JLabel();
        spnNivel = new javax.swing.JSpinner();
        sldPlazasLibres = new javax.swing.JSlider();
        chkPartidoAbierto = new javax.swing.JCheckBox();
        rbClase = new javax.swing.JRadioButton();
        rbLiga = new javax.swing.JRadioButton();
        rbAmistoso = new javax.swing.JRadioButton();
        cbHora = new javax.swing.JComboBox<>();
        lblVolver = new javax.swing.JLabel();
        lblEnviar = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        validationPanel1 = new org.netbeans.validation.api.ui.swing.ValidationPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        pnlBackground.setBackground(new java.awt.Color(204, 204, 204));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/raquetas.jpg"))); // NOI18N
        pnlBackground.add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 30, 30));

        lblExit.setBackground(new java.awt.Color(204, 204, 204));
        lblExit.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flechaVolver.jpg"))); // NOI18N
        lblExit.setToolTipText("");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.setOpaque(true);
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        pnlBackground.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        lblTitulo.setBackground(new java.awt.Color(204, 204, 204));
        lblTitulo.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 51, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Club de Pádel - Nueva Reserva");
        lblTitulo.setToolTipText("Título");
        lblTitulo.setOpaque(true);
        lblTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblTituloMouseDragged(evt);
            }
        });
        lblTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTituloMousePressed(evt);
            }
        });
        pnlBackground.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        lblReserva.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblReserva.setText("Datos de la reserva");
        pnlBackground.add(lblReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        lblCliente.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblCliente.setText("Datos del cliente");
        pnlBackground.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        lblNombre.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblNombre.setText("Nombre:");
        pnlBackground.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtNombre.setBackground(new java.awt.Color(204, 204, 204));
        txtNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setText("Introduzca su nombre y apellidos");
        txtNombre.setBorder(null);
        txtNombre.setName("Nombre"); // NOI18N
        txtNombre.setOpaque(true);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        pnlBackground.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 690, 20));

        sptNombre.setOpaque(true);
        pnlBackground.add(sptNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 690, -1));

        lblTelefono.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblTelefono.setText("Teléfono:");
        pnlBackground.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        cbPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ES", "PT", "FR" }));
        cbPais.setToolTipText("Seleccione el país para la asignación del prefijo");
        cbPais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbPaisMousePressed(evt);
            }
        });
        cbPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaisActionPerformed(evt);
            }
        });
        pnlBackground.add(cbPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        txtPrefijo.setEditable(false);
        txtPrefijo.setText("+34");
        txtPrefijo.setToolTipText("Se asigna automáticamente en función de la selección del país");
        txtPrefijo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPrefijoMousePressed(evt);
            }
        });
        txtPrefijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrefijoActionPerformed(evt);
            }
        });
        pnlBackground.add(txtPrefijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 52, -1));

        txtTelefono.setBackground(new java.awt.Color(204, 204, 204));
        txtTelefono.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefono.setText("Introduzca número de teléfono");
        txtTelefono.setBorder(null);
        txtTelefono.setName("Telefono"); // NOI18N
        txtTelefono.setOpaque(true);
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        pnlBackground.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 290, 20));

        sptTelefono.setOpaque(true);
        pnlBackground.add(sptTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 290, -1));

        lblFecha.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblFecha.setText("Fecha de reserva:");
        pnlBackground.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        spnFecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.ERA));
        spnFecha.setToolTipText("Introduzca fecha de la reserva");
        spnFecha.setEditor(new javax.swing.JSpinner.DateEditor(spnFecha, "dd/MM/yyyy"));
        JTextField editorFecha = ((JSpinner.DateEditor)
            spnFecha.getEditor()).getTextField();

        editorFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                rellenarPlaceHolders();
            }
        });

        spnFecha.addChangeListener(e -> {
            rellenarPlaceHolders();
        });
        spnFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                spnFechaMousePressed(evt);
            }
        });
        pnlBackground.add(spnFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 133, -1));

        lblHora.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblHora.setText("Hora de reserva:");
        pnlBackground.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        lblTipo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblTipo.setText("Tipo de reserva:");
        pnlBackground.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jSeparator1.setOpaque(true);
        pnlBackground.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 770, -1));

        lblNivel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblNivel.setText("Nivel de partido amistoso:");
        pnlBackground.add(lblNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        lblPlazas.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblPlazas.setText("Nº plazas libres:");
        pnlBackground.add(lblPlazas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        lblAbierto.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblAbierto.setText("Partido abierto:");
        pnlBackground.add(lblAbierto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        spnNivel.setModel(new javax.swing.SpinnerListModel(new String[] {"Iniciación", "Medio", "Medio-alto", "Alto"}));
        spnNivel.setToolTipText("Indique el nivel de los jugadores");
        JTextField editorNivel = ((JSpinner.DefaultEditor)
            spnNivel.getEditor()).getTextField();

        editorNivel.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                rellenarPlaceHolders();
            }
        });

        spnNivel.addChangeListener(e -> {
            rellenarPlaceHolders();
        });
        spnNivel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                spnNivelMousePressed(evt);
            }
        });
        pnlBackground.add(spnNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 343, -1));

        sldPlazasLibres.setMajorTickSpacing(1);
        sldPlazasLibres.setMaximum(3);
        sldPlazasLibres.setMinimum(1);
        sldPlazasLibres.setPaintLabels(true);
        sldPlazasLibres.setPaintTicks(true);
        sldPlazasLibres.setSnapToTicks(true);
        sldPlazasLibres.setToolTipText("Seleccione las plazas libres");
        sldPlazasLibres.setValue(1);
        sldPlazasLibres.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sldPlazasLibres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sldPlazasLibresMousePressed(evt);
            }
        });
        pnlBackground.add(sldPlazasLibres, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 343, -1));

        chkPartidoAbierto.setText("(Los jugadores se pueden apuntar por la web)");
        chkPartidoAbierto.setToolTipText("Marque si busca jugadores externos en la web");
        chkPartidoAbierto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chkPartidoAbiertoMousePressed(evt);
            }
        });
        chkPartidoAbierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPartidoAbiertoActionPerformed(evt);
            }
        });
        pnlBackground.add(chkPartidoAbierto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 343, -1));

        grupoTipoReserva.add(rbClase);
        rbClase.setText("Clase");
        rbClase.setToolTipText("Reserva de tipo clase");
        rbClase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbClaseMousePressed(evt);
            }
        });
        rbClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbClaseActionPerformed(evt);
            }
        });
        pnlBackground.add(rbClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 100, -1));
        gestionarCamposAmistoso();

        grupoTipoReserva.add(rbLiga);
        rbLiga.setText("Liga");
        rbLiga.setToolTipText("Reserva de tipo liga");
        rbLiga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbLigaMousePressed(evt);
            }
        });
        rbLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLigaActionPerformed(evt);
            }
        });
        pnlBackground.add(rbLiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 100, -1));
        gestionarCamposAmistoso();

        grupoTipoReserva.add(rbAmistoso);
        rbAmistoso.setText("Amistoso");
        rbAmistoso.setToolTipText("Reserva de tipo amistoso");
        rbAmistoso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbAmistosoMousePressed(evt);
            }
        });
        rbAmistoso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAmistosoActionPerformed(evt);
            }
        });
        pnlBackground.add(rbAmistoso, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 100, -1));
        gestionarCamposAmistoso();

        cbHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "17:00", "18:30", "20:00", "21:30" }));
        cbHora.setToolTipText("Seleccione uno de los turnos disponibles");
        cbHora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbHoraMousePressed(evt);
            }
        });
        cbHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHoraActionPerformed(evt);
            }
        });
        pnlBackground.add(cbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 133, -1));

        lblVolver.setBackground(new java.awt.Color(245, 245, 245));
        lblVolver.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVolver.setText("Volver");
        lblVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVolver.setOpaque(true);
        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVolverMouseExited(evt);
            }
        });
        pnlBackground.add(lblVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 150, 50));

        lblEnviar.setBackground(new java.awt.Color(245, 245, 245));
        lblEnviar.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblEnviar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnviar.setText("Enviar Reserva");
        lblEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEnviar.setOpaque(true);
        lblEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEnviarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEnviarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEnviarMouseExited(evt);
            }
        });
        pnlBackground.add(lblEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, 150, 50));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoPadel2.jpg"))); // NOI18N
        lblFondo.setText("jLabel1");
        lblFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblFondoMousePressed(evt);
            }
        });
        pnlBackground.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 650));
        pnlBackground.add(validationPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 590, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaisActionPerformed

        // Obtenemos el texto de la opción seleccionada
        String seleccion = cbPais.getSelectedItem().toString();

        // Estructura para asignar el prefijo según el país
        // Estructura para asignar el prefijo según el país
        switch (seleccion) {
            case "ES":
                txtPrefijo.setText("+34");
                break;
            case "FR":
                txtPrefijo.setText("+33");
                break;
            case "PT":
                txtPrefijo.setText("+351");
                break;
            default:
                txtPrefijo.setText("");
                break;
        }
    }//GEN-LAST:event_cbPaisActionPerformed

    private void txtPrefijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrefijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrefijoActionPerformed

    private void cbHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbHoraActionPerformed

    private void rbClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbClaseActionPerformed
        gestionarCamposAmistoso();
    }//GEN-LAST:event_rbClaseActionPerformed

    private void rbLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLigaActionPerformed
        gestionarCamposAmistoso();
    }//GEN-LAST:event_rbLigaActionPerformed

    private void rbAmistosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAmistosoActionPerformed
        gestionarCamposAmistoso();
    }//GEN-LAST:event_rbAmistosoActionPerformed

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        lblExit.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        lblExit.setBackground(Color.white);
    }//GEN-LAST:event_lblExitMouseExited

    private void lblTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_lblTituloMousePressed

    private void lblTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_lblTituloMouseDragged

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void chkPartidoAbiertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPartidoAbiertoActionPerformed
        gestionarCamposAmistoso();
    }//GEN-LAST:event_chkPartidoAbiertoActionPerformed

    private void lblVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblVolverMouseClicked

    private void lblVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseEntered
        lblVolver.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_lblVolverMouseEntered

    private void lblVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseExited
        lblVolver.setBackground(Color.white);
    }//GEN-LAST:event_lblVolverMouseExited

    private void lblEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnviarMouseClicked
        if (!lblEnviar.isEnabled()) {
            return;
        }

        // 1. Extraer la fecha y darle formato de texto para el mensaje
        // Aunque el Spinner solo muestre dd/MM/yyyy, getValue() devuelve un objeto Date complejo
        java.text.SimpleDateFormat formato = new java.text.SimpleDateFormat("dd/MM/yyyy");
        String fechaSeleccionada = formato.format(spnFecha.getValue());

        // 2. Extraer la hora seleccionada del ComboBox
        String horaSeleccionada = cbHora.getSelectedItem().toString();

        // 3. Extraer el nombre para personalizar el mensaje
        String cliente = lblNombre.getText();

        // 4. Construir el cuerpo del mensaje
        String mensaje = "Reserva confirmada con éxito.\n\n"
                + "Cliente: " + cliente + "\n"
                + "Fecha: " + fechaSeleccionada + "\n"
                + "Hora: " + horaSeleccionada;

        // 5. Mostrar el mensaje al usuario
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Confirmación de Reserva", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // 6. Cerrar el diálogo
        this.dispose();
    }//GEN-LAST:event_lblEnviarMouseClicked

    private void lblEnviarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnviarMouseEntered
        lblEnviar.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_lblEnviarMouseEntered

    private void lblEnviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnviarMouseExited
        lblEnviar.setBackground(Color.white);
    }//GEN-LAST:event_lblEnviarMouseExited

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        if (txtNombre.getText().equals("Introduzca su nombre y apellidos")) {
            txtNombre.setText("");
            txtNombre.setForeground(Color.black);
        }
        if (txtTelefono.getText().isEmpty()) {
            txtTelefono.setText("Introduzca número de teléfono");
            txtTelefono.setForeground(new Color(102, 102, 102));
        }
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
        if (txtTelefono.getText().equals("Introduzca número de teléfono")) {
            txtTelefono.setText("");
            txtTelefono.setForeground(Color.black);
        }
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Introduzca su nombre y apellidos");
            txtNombre.setForeground(new Color(102, 102, 102));
        }
    }//GEN-LAST:event_txtTelefonoMousePressed

    private void lblFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFondoMousePressed
        rellenarPlaceHolders();
    }//GEN-LAST:event_lblFondoMousePressed

    private void cbPaisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbPaisMousePressed
        rellenarPlaceHolders();
    }//GEN-LAST:event_cbPaisMousePressed

    private void txtPrefijoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrefijoMousePressed
        rellenarPlaceHolders();
    }//GEN-LAST:event_txtPrefijoMousePressed

    private void spnFechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spnFechaMousePressed
        rellenarPlaceHolders();
    }//GEN-LAST:event_spnFechaMousePressed

    private void cbHoraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbHoraMousePressed
        rellenarPlaceHolders();
    }//GEN-LAST:event_cbHoraMousePressed

    private void rbClaseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbClaseMousePressed
        rellenarPlaceHolders();
    }//GEN-LAST:event_rbClaseMousePressed

    private void rbLigaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbLigaMousePressed
        rellenarPlaceHolders();
    }//GEN-LAST:event_rbLigaMousePressed

    private void rbAmistosoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbAmistosoMousePressed
        rellenarPlaceHolders();
    }//GEN-LAST:event_rbAmistosoMousePressed

    private void spnNivelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spnNivelMousePressed
        rellenarPlaceHolders();
    }//GEN-LAST:event_spnNivelMousePressed

    private void chkPartidoAbiertoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkPartidoAbiertoMousePressed
        rellenarPlaceHolders();
    }//GEN-LAST:event_chkPartidoAbiertoMousePressed

    private void sldPlazasLibresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldPlazasLibresMousePressed
        rellenarPlaceHolders();
    }//GEN-LAST:event_sldPlazasLibresMousePressed

    /**
     * @param args the command line arguments
     */
    private void gestionarCamposAmistoso() {
        // Esta línea es la clave: devuelve 'true' solo si Amistoso está marcado
        boolean esAmistoso = rbAmistoso.isSelected();

        // Si esAmistoso es false (porque está pulsado Liga o Clase), se deshabilitan:
        spnNivel.setEnabled(esAmistoso);
        chkPartidoAbierto.setEnabled(esAmistoso);

        // Lógica para el Slider de plazas
        if (esAmistoso && chkPartidoAbierto.isSelected()) {
            sldPlazasLibres.setEnabled(true);
        } else {
            sldPlazasLibres.setEnabled(false);
        }
    }

    private void rellenarPlaceHolders() {
        if (txtNombre.getText().isEmpty()) {
            txtNombre.setText("Introduzca su nombre y apellidos");
            txtNombre.setForeground(new Color(102, 102, 102));
        }
        if (txtTelefono.getText().isEmpty()) {
            txtTelefono.setText("Introduzca número de teléfono");
            txtTelefono.setForeground(new Color(102, 102, 102));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbHora;
    private javax.swing.JComboBox<String> cbPais;
    private javax.swing.JCheckBox chkPartidoAbierto;
    private javax.swing.ButtonGroup grupoTipoReserva;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAbierto;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblEnviar;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPlazas;
    private javax.swing.JLabel lblReserva;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JRadioButton rbAmistoso;
    private javax.swing.JRadioButton rbClase;
    private javax.swing.JRadioButton rbLiga;
    private javax.swing.JSlider sldPlazasLibres;
    private javax.swing.JSpinner spnFecha;
    private javax.swing.JSpinner spnNivel;
    private javax.swing.JSeparator sptNombre;
    private javax.swing.JSeparator sptTelefono;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrefijo;
    private javax.swing.JTextField txtTelefono;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel1;
    // End of variables declaration//GEN-END:variables
}
